"""One normalized chat/tool-use interface over Claude, OpenAI, and local Ollama."""

from .adapter import Adapter
from .adapters.claude import ClaudeAdapter
from .adapters.ollama import OllamaLocalAdapter
from .adapters.openai import OpenAIAdapter
from .errors import (
    APIError,
    AuthError,
    ContextOverflowError,
    DucktapeError,
    RateLimitError,
    RequestTimeoutError,
    ServerError,
    UnsupportedBlockError,
)
from .provider import Config, Provider
from .types import (
    Base64DocumentBlock,
    Base64ImageBlock,
    Base64Str,
    Block,
    BlockStopEvent,
    DocumentBlock,
    ImageBlock,
    JsonSchema,
    Message,
    MessageStopEvent,
    MimeType,
    Response,
    StopReason,
    StreamEvent,
    TextBlock,
    TextDeltaEvent,
    ThinkingBlock,
    ThinkingDeltaEvent,
    ToolCallId,
    ToolDef,
    ToolResultBlock,
    ToolUseBlock,
    ToolUseDeltaEvent,
    ToolUseStartEvent,
    UrlDocumentBlock,
    UrlImageBlock,
    Usage,
)

__all__ = [
    "APIError",
    "Adapter",
    "AuthError",
    "Base64DocumentBlock",
    "Base64ImageBlock",
    "Base64Str",
    "Block",
    "BlockStopEvent",
    "ClaudeAdapter",
    "Config",
    "ContextOverflowError",
    "DocumentBlock",
    "DucktapeError",
    "ImageBlock",
    "JsonSchema",
    "Message",
    "MessageStopEvent",
    "MimeType",
    "OllamaLocalAdapter",
    "OpenAIAdapter",
    "Provider",
    "RateLimitError",
    "RequestTimeoutError",
    "Response",
    "ServerError",
    "StopReason",
    "StreamEvent",
    "TextBlock",
    "TextDeltaEvent",
    "ThinkingBlock",
    "ThinkingDeltaEvent",
    "ToolCallId",
    "ToolDef",
    "ToolResultBlock",
    "ToolUseBlock",
    "ToolUseDeltaEvent",
    "ToolUseStartEvent",
    "UnsupportedBlockError",
    "UrlDocumentBlock",
    "UrlImageBlock",
    "Usage",
]
